### ISSUE TITLE
使用t/add接口一直返回error content len

### ISSUE THREAD

**Issue by Yao4github** [heloyue/TCWeiboSDK-LightVersion#3]
◎、调用代码：
    NSMutableDictionary *params = [[NSMutableDictionary alloc]initWithObjectsAndKeys:@"json",@"format",
                                   @"hi,weibo sdk", @"content",
                                   nil];
    [wbapi requestWithParams:params apiName:@"t/add" httpMethod:@"POST" delegate:self];

◎、看接口文档clientip是必须的改为：
    NSMutableDictionary *params = [[NSMutableDictionary alloc]initWithObjectsAndKeys:@"json",@"format",
                                   @"hi,weibo sdk", @"content",
                                   @"113.10.205.45",@"clientip",
                                   nil];
    [wbapi requestWithParams:params apiName:@"t/add" httpMethod:@"POST" delegate:self];

◎、一直返回
result = {"data":null,"detailerrinfo":{"accesstoken":"","apiname":"weibo.t.add","appkey":"","clientip":"113.10.205.45","cmd":0,"proctime":1,"ret1":2,"ret2":1,"ret3":2,"ret4":1327727882,"timestamp":1373434127},"errcode":2,"msg":"error content len","ret":1,"seqid":5898854658680545602}

能否确认下是不是我写得不正确？或者说正确的是怎么样的？

**Comment by heloyue** [comment]
谢谢反馈，测试了一下是bug， 已经修复。
请重新下载更新一下静态库，再测试一下

**Comment by Yao4github** [comment]
谢谢及时fix
