### ISSUE TITLE
发现一个无法回跳回第三方APP的问题

### ISSUE THREAD

**Issue by Yao4github** [heloyue/TCWeiboSDK-LightVersion#4]
场景描述：
A：第三方客户端
B：腾讯微博客户端

前提条件：未登陆 腾讯微博客户端

A中去授权，跳转到B，在B中输入用户名/密码，登陆B客户端

结果：直接到B客户端无法回调到A了

PS：B客户端的问题？

**Comment by heloyue** [comment]
这是一个bug，是微博客户端的，下个版本修复。

**Comment by heloyue** [comment]
已知bug，谢谢您的反馈。

**Comment by Yao4github** [comment]
好的，谢谢回馈
